language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

branches:
  only:
    - master

codecov: true

# after_success:
#   - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
#   - julia --project=test/coverage test/coverage/coverage.jl
#   - julia -e 'using Pkg; cd(Pkg.dir("MatrixEquations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
 
jobs:
  allow_failures:
    - julia: 1.0
    - julia: 1.1
    - julia: 1.4
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip